### ISSUE TITLE
comparison with chrome-remote-multiplex

### ISSUE THREAD

**Issue by graingert** [sidorares/crmux#18]
There seems to be some repeated work between chrome-remote-multiplex and crmux:
https://npmcompare.com/compare/chrome-remote-multiplex,crmux

It would be good for you, @sidorares, and @johnspackman to work together on one module.

**Comment by johnspackman** [comment]
I definitely would have used [crmux](https://github.com/sidorares/crmux) instead of writing [chrome-remote-multiplex](https://github.com/johnspackman/chrome-remote-multiplex) if I'd known about it at the time - my google-fu must have been failing me! :)

I've only had a quick look at the code, but it looks like the main difference is that chrome-remote-multiplex extracts the Chrome APIs so that messages can be replayed to new connections, eg `enable`/`disable` and execution contexts.

**Comment by graingert** [comment]
> extracts the Chrome APIs so that messages can be replayed to new connections, eg enable/disable and execution contexts.

extracts?

**Comment by johnspackman** [comment]
The devtools protocol sends various messages, in a OO form - eg there is a `Runtime` module, a `Page` module - and when sent it's just as linear data, eg a message saying that `Runtime.enable` is being called, or a new execution context is created with `Runtime.executionContextCreated`.  The client and server expect the other to maintain state, although in practice this often does not matter there are times where connecting a new client to the server will trip over each other - if you have two clients, both send `Runtime.enable` and later `Runtime.disable`, you would not want the server (ie Chrome) to receive enable/enable/disable/disable.  Similarly with execution contexts, when the second client connects, it needs to be sent the execution contexts so that it can connect to the debugger.

[chrome-remote-multiplex](https://github.com/johnspackman/chrome-remote-multiplex) creates shadow/proxy instances of Runtime and other APIs so that it can act as stateful proxy server.  Take a look at [multiplex.js](https://github.com/johnspackman/chrome-remote-multiplex/blob/master/src/multiplex.js#L157-L218)

**Comment by sidorares** [comment]
@johnspackman also I just recently discovered that chrome 63 ( canary atm ) does not forces other connections to close, so both crmux and chrome-remote-multiplex are going to be redundant soon ( personally I started to just use canary when I need multiple clients ). @paulirish can you confirm this? Has not been mentioned anywhere

**Comment by paulirish** [comment]
yes i can both confirm that this works and it hasn't been mentioned anywhere. :)

**Comment by sidorares** [comment]
Happy days! One unnecessary tool less

**Comment by graingert** [comment]
@sidorares 2
